<?php

/**
 * @file
 * Code for the Hedley item feature.
 */

include_once 'hedley_item.features.inc';

/**
 * Implements hook_node_insert().
 */
function hedley_item_node_insert($node) {
  hedley_item_trigger_pusher_on_item_data_change($node);
}

/**
 * Implements hook_node_update().
 */
function hedley_item_node_update($node) {
  if ($node->type != 'item') {
    return;
  }
  // Make sure we get updated data.
  entity_get_controller('node')->resetCache();
  hedley_item_trigger_pusher_on_item_data_change($node);
}

/**
 * Trigger a pusher event for a Item data.
 *
 * @param object $node
 *   A Item data node type.
 */
function hedley_item_trigger_pusher_on_item_data_change($node) {
  if ($node->type != 'item') {
    return;
  }

  if ($node->status == NODE_NOT_PUBLISHED) {
    // Node is not published.
    return;
  }

  $account = user_load($node->uid);

  $handler = restful_get_restful_handler('items');
  $handler->setAccount($account);
  $data = $handler->get($node->nid);

  hedley_pusher_trigger_event('general', 'item__update', $data[0]);
}
