APIVersion: v1.7.1
omit_containers: []
instrumentation_opt_in: false
last_used_version: v1.7.1

# You can turn off usage of the dba (phpmyadmin) container and/or 
# ddev-ssh-agent containers with
# omit_containers["dba", "ddev-ssh-agent"]

# and you can opt in or out of sending instrumentation the ddev developers with 
# instrumentation_opt_in: true # or false
